use std::sync::atomic::AtomicU32;

use ash::vk;

use crate::{
    Error, FrameContext, RenderStorage, RenderTarget, RenderTechnique, Renderer, Result,
    ShaderVertVertex,
};

const COMPILED_DEPTH_VERT_SHADER: &[u8] = include_bytes!("../../shaders/depth.vert.spv");
const COMPILED_DEPTH_FRAG_SHADER: &[u8] = include_bytes!("../../shaders/depth.frag.spv");

pub struct DepthResources {
    id: u32,
    per_frame_descriptor_set_layout_handle: crate::DescriptorSetLayoutResourceHandle,
    pipeline_layout_handle: crate::PipelineLayoutResourceHandle,
    vert_module_handle: crate::ShaderModuleResourceHandle,
    frag_module_handle: crate::ShaderModuleResourceHandle,
}

static NEXT_DEPTH_RESOURCES_ID: AtomicU32 = AtomicU32::new(0);
impl DepthResources {
    fn get_id() -> u32 {
        NEXT_DEPTH_RESOURCES_ID.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
    }
    pub fn new(renderer: &mut Renderer) -> crate::Result<Self> {
        let descriptor_set_layout_bindings: &[crate::DescriptorSetLayoutBindingInfo] = &[
            crate::DescriptorSetLayoutBindingInfo {
                binding: 0,
                ty: vk::DescriptorType::STORAGE_BUFFER,
                count: 1,
                stage_flags: vk::ShaderStageFlags::VERTEX | vk::ShaderStageFlags::FRAGMENT,
            },
            crate::DescriptorSetLayoutBindingInfo {
                binding: 1,
                ty: vk::DescriptorType::UNIFORM_BUFFER,
                count: 1,
                stage_flags: vk::ShaderStageFlags::VERTEX | vk::ShaderStageFlags::FRAGMENT,
            },
        ];

        let per_frame_descriptor_set_layout_desc = crate::DescriptorSetLayoutDescription {
            bindings: descriptor_set_layout_bindings.into(),
        };
        let per_frame_descriptor_set_layout_handle = renderer
            .descriptor_set_layouts_mut()
            .access_or_create(per_frame_descriptor_set_layout_desc)?;

        let pipeline_layout_desc = crate::PipelineLayoutDescription {
            descriptor_set_layouts: Box::new([per_frame_descriptor_set_layout_handle]),
            bind_point: vk::PipelineBindPoint::GRAPHICS,
        };

        let pipeline_layout_handle =
            renderer.access_or_create_pipeline_layout(pipeline_layout_desc)?;

        // TODO: it seems like this could be generated by build.rs or a macro?
        const VERTEX_ATTRIBUTE_DESCRIPTIONS: &[vk::VertexInputAttributeDescription] =
            &[vk::VertexInputAttributeDescription {
                location: 0,
                binding: 0,
                format: vk::Format::R32G32B32_SFLOAT,
                offset: std::mem::offset_of!(crate::ShaderVertVertex, position) as u32,
            }];
        let vertex_input_bindings = &[vk::VertexInputBindingDescription {
            binding: 0,
            stride: std::mem::size_of::<ShaderVertVertex>() as u32,
            input_rate: vk::VertexInputRate::VERTEX,
        }];
        let vert_module_desc = crate::ShaderModuleDescription::Internal {
            stage: vk::ShaderStageFlags::VERTEX,
            spv: COMPILED_DEPTH_VERT_SHADER,
            entry_point_name: crate::ENTRY_POINT_NAME_DEPTH_VERT,
            vertex_attribute_descriptions: VERTEX_ATTRIBUTE_DESCRIPTIONS,
            vertex_input_bindings,
        };
        let vert_module_handle = renderer
            .shader_modules_mut()
            .access_or_create(vert_module_desc)?;

        let frag_module_desc = crate::ShaderModuleDescription::Internal {
            stage: vk::ShaderStageFlags::FRAGMENT,
            spv: COMPILED_DEPTH_FRAG_SHADER,
            entry_point_name: crate::ENTRY_POINT_NAME_DEPTH_FRAG,
            vertex_attribute_descriptions: &[],
            vertex_input_bindings: &[],
        };
        let frag_module_handle = renderer
            .shader_modules_mut()
            .access_or_create(frag_module_desc)?;

        Ok(Self {
            id: Self::get_id(),
            per_frame_descriptor_set_layout_handle,
            pipeline_layout_handle,
            vert_module_handle,
            frag_module_handle,
        })
    }
    #[inline]
    pub fn bind<Target, Storage, Handle>(
        &self,
        cmd: vk::CommandBuffer,
        renderer: &mut Renderer,
        target: &Target,
        storage: &Storage,
    ) -> Result<()>
    where
        Handle: Copy + Clone,
        Target: RenderTarget<ImageHandle = Handle>,
        Storage: RenderStorage<ImageHandle = Handle>,
    {
        let pipeline = {
            let mut color_formats: Vec<vk::Format> = Vec::with_capacity(8);
            for target_image in target.color_images().iter() {
                let img = storage
                    .get_image(target_image.handle)
                    .ok_or(Error::ResourceMissing)?;
                color_formats.push(img.format);
            }

            let depth_format = if let Some(img_handle) = target.depth_image() {
                let img = storage
                    .get_image(img_handle)
                    .ok_or(Error::ResourceMissing)?;
                Some(img.format)
            } else {
                None
            };

            let pipeline_desc = crate::PipelineDescription::DynamicGraphics {
                pipeline_layout: self.pipeline_layout_handle,
                vert_shader: self.vert_module_handle,
                frag_shader: self.frag_module_handle,
                topology: vk::PrimitiveTopology::TRIANGLE_LIST,
                color_formats: color_formats.into_boxed_slice(),
                depth_format,
                stencil_format: None,
                samples: vk::SampleCountFlags::TYPE_1,
            };
            let pipeline_handle = renderer.pipelines.access_or_create(
                pipeline_desc,
                &mut renderer.pipeline_layouts,
                &mut renderer.shader_modules,
            )?;
            let pipeline = renderer
                .pipelines
                .get(pipeline_handle)
                .ok_or(Error::ResourceMissing)?;

            *pipeline
        };
        unsafe {
            renderer
                .device
                .cmd_bind_pipeline(cmd, vk::PipelineBindPoint::GRAPHICS, pipeline);
        }
        Ok(())
    }
}

#[allow(dead_code)]
pub struct DepthTechnique {
    depth_resources_id: u32,
    device: vulkan::SharedDeviceRef,
    descriptor_pool: vk::DescriptorPool,
    per_frame_descriptor_sets: [vk::DescriptorSet; crate::MAX_FRAME_COUNT as usize],
}

impl Drop for DepthTechnique {
    fn drop(&mut self) {
        unsafe {
            self.device.destroy_descriptor_pool(self.descriptor_pool);
        }
    }
}

impl DepthTechnique {
    pub fn new(
        renderer: &mut crate::Renderer,
        resources: &mut DepthResources,
    ) -> crate::Result<Self> {
        let device = renderer.device.clone();

        let descriptor_pool = {
            let pool_sizes = [
                vk::DescriptorPoolSize {
                    ty: vk::DescriptorType::UNIFORM_BUFFER,
                    descriptor_count: crate::MAX_FRAME_COUNT as u32,
                },
                vk::DescriptorPoolSize {
                    ty: vk::DescriptorType::STORAGE_BUFFER,
                    descriptor_count: crate::MAX_FRAME_COUNT as u32,
                },
            ];
            let create_info = vk::DescriptorPoolCreateInfo {
                max_sets: crate::MAX_FRAME_COUNT as u32,
                pool_size_count: pool_sizes.len() as u32,
                p_pool_sizes: pool_sizes.as_ptr(),
                ..Default::default()
            };

            unsafe { device.create_descriptor_pool(&create_info) }?
        };

        let per_frame_descriptor_sets: [vk::DescriptorSet; crate::MAX_FRAME_COUNT as usize] = {
            let per_frame_set_layout = *renderer
                .descriptor_set_layouts_mut()
                .get(resources.per_frame_descriptor_set_layout_handle)
                .unwrap();
            let set_layouts = [per_frame_set_layout; crate::MAX_FRAME_COUNT as usize];
            let alloc_info = vk::DescriptorSetAllocateInfo {
                descriptor_pool,
                descriptor_set_count: set_layouts.len() as u32,
                p_set_layouts: set_layouts.as_ptr(),
                ..Default::default()
            };
            let sets = unsafe { device.allocate_descriptor_sets(&alloc_info) }?;

            sets.try_into()
                .expect("Incorrect number of descriptor sets")
        };

        Ok(Self {
            device,
            depth_resources_id: resources.id,
            descriptor_pool,
            per_frame_descriptor_sets,
        })
    }
    pub fn update_context(
        &mut self,
        ctx: &crate::FrameContext,
        light_data_range: &vulkan::AllocationRange,
        instance_data_range: &vulkan::AllocationRange,
    ) {
        let light_infos: Box<[vk::DescriptorBufferInfo]> = (0..crate::MAX_FRAME_COUNT as usize)
            .map(|i| vk::DescriptorBufferInfo {
                buffer: ctx.frames()[i].allocator().uniform_allocator().buffer(),
                offset: light_data_range.offset,
                range: light_data_range.size,
            })
            .collect();

        let instance_infos: Box<[vk::DescriptorBufferInfo]> = (0..crate::MAX_FRAME_COUNT as usize)
            .map(|i| vk::DescriptorBufferInfo {
                buffer: ctx.frames()[i].allocator().storage_allocator().buffer(),
                offset: instance_data_range.offset,
                range: instance_data_range.size,
            })
            .collect();

        let writes: Box<[vk::WriteDescriptorSet]> = (0..crate::MAX_FRAME_COUNT as usize)
            .flat_map(|i| {
                [
                    vk::WriteDescriptorSet {
                        dst_set: self.per_frame_descriptor_sets[i],
                        dst_binding: 0,
                        descriptor_count: 1,
                        p_buffer_info: &instance_infos[i],
                        descriptor_type: vk::DescriptorType::STORAGE_BUFFER,
                        ..Default::default()
                    },
                    vk::WriteDescriptorSet {
                        dst_set: self.per_frame_descriptor_sets[i],
                        dst_binding: 1,
                        descriptor_count: 1,
                        p_buffer_info: &light_infos[i],
                        descriptor_type: vk::DescriptorType::UNIFORM_BUFFER,
                        ..Default::default()
                    },
                ]
                .into_iter()
            })
            .collect();

        unsafe { self.device.update_descriptor_sets(&writes, &[]) };
    }
}

impl RenderTechnique for DepthTechnique {
    type TechniqueResources = DepthResources;
    fn bind(
        &self,
        cmd: vk::CommandBuffer,
        ctx: &FrameContext,
        resources: &Self::TechniqueResources,
        renderer: &Renderer,
    ) -> crate::Result<()> {
        debug_assert!(self.depth_resources_id == resources.id);

        let current_frame_index = ctx.frame_index;

        let layout = renderer
            .pipeline_layouts
            .get(resources.pipeline_layout_handle)
            .ok_or(crate::Error::ResourceMissing)?
            .raw;

        unsafe {
            // bind per frame ds
            let sets = &[self.per_frame_descriptor_sets[current_frame_index]];
            let dynamic_offsets = &[];
            self.device.cmd_bind_descriptor_sets(
                cmd,
                vk::PipelineBindPoint::GRAPHICS,
                layout,
                0,
                sets,
                dynamic_offsets,
            );
        }

        Ok(())
    }
}
