bindings:
  - command: move_forward
    input: w
    event: hold

  - command: move_left
    input: a
    event: hold

  - command: move_backward
    input: s
    event: hold

  - command: move_right
    input: d
    event: hold

  - command: move_up
    input: space
    event: hold

  - command: move_down
    input: ctrl_left
    event: hold

  - command: rotate
    input: mouse_moved
    event: movement
    requires: mouse_move_requirement

  - command: mouse_move_requirement
    input: mouse1
    event: toggle

  - command: use_fps_camera
    input: "1"
    event: press

  - command: use_orbit_camera
    input: "2"
    event: press

  - command: zoom_in
    input: "mousewheel_up"
    event: press

  - command: zoom_out
    input: "mousewheel_down"
    event: press

options:
  default_camera: "orbit"
  fov_y: 65.0
  mouse_sensitivity: 75.0
  derive_normals: true
  model_up: "-z"
  model_right: "+x"
  model_forward: "+y"
